# Generated by Django 3.0.5 on 2021-07-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0010_auto_20210710_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='sync',
            field=models.BooleanField(default=False),
        ),
    ]
