# Generated by Django 3.0.5 on 2021-09-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0012_auto_20210806_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='mes',
            field=models.CharField(default=9, max_length=10),
        ),
        migrations.AlterField(
            model_name='sorteodetalle',
            name='mes',
            field=models.CharField(default=9, max_length=10),
        ),
    ]
