# Generated by Django 3.0.5 on 2022-01-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0014_auto_20211013_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='mes',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='sorteodetalle',
            name='mes',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
