# Generated by Django 3.0.5 on 2024-02-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0015_auto_20220121_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='mes',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='sorteodetalle',
            name='mes',
            field=models.CharField(default=2, max_length=10),
        ),
    ]
