# Generated by Django 3.0.5 on 2021-08-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoconexion',
            old_name='fecha_internet',
            new_name='fecha_chuequeo',
        ),
        migrations.RenameField(
            model_name='estadoconexion',
            old_name='ip_online',
            new_name='ip_cliente',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='emby',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='ftp',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='ip_emby',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='ip_ftp',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='ip_internet',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='ip_jc',
        ),
        migrations.RemoveField(
            model_name='estadoconexion',
            name='jc',
        ),
    ]
