# Generated by Django 3.0.5 on 2021-08-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20210806_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoconexion',
            old_name='fecha_chuequeo',
            new_name='fecha_chequeo',
        ),
    ]
