# Generated by Django 3.0.5 on 2021-08-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20210806_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoconexion',
            name='emby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadoconexion',
            name='ftp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadoconexion',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadoconexion',
            name='jc',
            field=models.BooleanField(default=False),
        ),
    ]
