# Generated by Django 3.0.5 on 2024-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_auto_20210806_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_cliente',
            field=models.CharField(default='127.0.0.1', help_text='format: ip:puerto', max_length=30),
            preserve_default=False,
        ),
    ]
