# Generated by Django 3.0.5 on 2021-10-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210521_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoservicio',
            name='int_duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estadoservicio',
            name='int_velocidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
